# Generated by Django 4.1.6 on 2023-02-02 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choices_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_txt',
            new_name='question_text',
        ),
    ]
